In [1]:
from optimizn.experiments.tsp.tsp_experiments import run_tsp_experiments

In [2]:
exp1_results = run_tsp_experiments(50, 1, 3)

Initial solution: [ 0 34 36 21 18 38  4 11 42 46 49 16 40 33 14 27 44 19 13 37 41 47 31 24
 32 20 45 48  2  1 15 39 17  5  6 22 10  9 29  7 26 25 35 23  8 12 28 30
  3 43]
Initial solution cost: 145.77367830990758
Iteration: 0 Current best solution: 145.77367830990758
Best cost updated to:144.66071450935183
Best cost updated to:144.29580816894727
Best cost updated to:143.14188543843642
Best cost updated to:143.08734183229714
Best cost updated to:142.48866405073605
Best cost updated to:140.31262221063807
Best cost updated to:139.6333812312969
Best cost updated to:139.61755380058227
Best cost updated to:139.4208244601103
Iteration: 10000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 429.3648768335075
Resetting candidate solution.
with cost: 462.1968912685878
Iteration: 20000 Current best solution: 139.4208244601103
Iteration: 30000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 451.33288319517425
Resetting candidate s

c:\Users\asathiya\anaconda3\envs\optimizn\lib\site-packages\optimizn-0.0.7-py3.9.egg\optimizn\combinatorial\anneal.py:64: RuntimeWarning: overflow encountered in exp
  eps = np.exp(cost_del / temprature)


Iteration: 130000 Current best solution: 139.4208244601103
Iteration: 140000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 470.51161057505476
Iteration: 150000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 405.8520525947879
Resetting candidate solution.
with cost: 443.60041767098943
Iteration: 160000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 424.77419306382745
Resetting candidate solution.
with cost: 467.72640874215386
Iteration: 170000 Current best solution: 139.4208244601103
Iteration: 180000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 488.881756354322
Resetting candidate solution.
with cost: 438.29265831941336
Iteration: 190000 Current best solution: 139.4208244601103
Resetting candidate solution.
with cost: 433.9828933095406
Resetting candidate solution.
with cost: 413.3984609843636
Iteration: 200000 Current best solution: 139.4208244

In [3]:
exp1_results

{'sa1': [139.4208244601103, 139.4208244601103, 139.4208244601103],
 'sa1_time': [60.00007772445679, 60.00011944770813, 60.00026607513428],
 'sa2': [135.12765196108037, 135.12765196108037, 134.53091653954118],
 'sa2_time': [60.00327920913696, 60.00393462181091, 60.00339460372925],
 'trad_bnb': [145.77367830990758, 145.77367830990758, 145.77367830990758],
 'trad_bnb_time': [65.1672854423523, 60.16127920150757, 60.26487922668457],
 'mod_bnb': [138.30797382698466, 138.30797382698466, 138.30797382698466],
 'mod_bnb_time': [60.01349902153015, 60.10207962989807, 60.11351776123047],
 'sa1_init_sol': array([ 0, 34, 36, 21, 18, 38,  4, 11, 42, 46, 49, 16, 40, 33, 14, 27, 44,
        19, 13, 37, 41, 47, 31, 24, 32, 20, 45, 48,  2,  1, 15, 39, 17,  5,
         6, 22, 10,  9, 29,  7, 26, 25, 35, 23,  8, 12, 28, 30,  3, 43]),
 'sa1_init_sol_cost': 145.77367830990758,
 'sa2_init_sol': [0,
  34,
  36,
  21,
  18,
  38,
  4,
  11,
  42,
  46,
  49,
  16,
  40,
  33,
  14,
  27,
  44,
  19,
  13,
  37,


In [4]:
exp1_results['sa1_init_sol_cost'], exp1_results['sa1_init_sol']

(145.77367830990758,
 array([ 0, 34, 36, 21, 18, 38,  4, 11, 42, 46, 49, 16, 40, 33, 14, 27, 44,
        19, 13, 37, 41, 47, 31, 24, 32, 20, 45, 48,  2,  1, 15, 39, 17,  5,
         6, 22, 10,  9, 29,  7, 26, 25, 35, 23,  8, 12, 28, 30,  3, 43]))

In [5]:
exp1_results['sa2_init_sol_cost'], exp1_results['sa2_init_sol']

(145.77367830990758,
 [0,
  34,
  36,
  21,
  18,
  38,
  4,
  11,
  42,
  46,
  49,
  16,
  40,
  33,
  14,
  27,
  44,
  19,
  13,
  37,
  41,
  47,
  31,
  24,
  32,
  20,
  45,
  48,
  2,
  1,
  15,
  39,
  17,
  5,
  6,
  22,
  10,
  9,
  29,
  7,
  26,
  25,
  35,
  23,
  8,
  12,
  28,
  30,
  3,
  43])

In [6]:
exp1_results['trad_bnb_init_sol_cost'], exp1_results['trad_bnb_init_sol']

(145.77367830990758,
 ([0,
   34,
   36,
   21,
   18,
   38,
   4,
   11,
   42,
   46,
   49,
   16,
   40,
   33,
   14,
   27,
   44,
   19,
   13,
   37,
   41,
   47,
   31,
   24,
   32,
   20,
   45,
   48,
   2,
   1,
   15,
   39,
   17,
   5,
   6,
   22,
   10,
   9,
   29,
   7,
   26,
   25,
   35,
   23,
   8,
   12,
   28,
   30,
   3,
   43],
  -1))

In [7]:
exp1_results['mod_bnb_init_sol_cost'], exp1_results['mod_bnb_init_sol']

(145.77367830990758,
 ([0,
   34,
   36,
   21,
   18,
   38,
   4,
   11,
   42,
   46,
   49,
   16,
   40,
   33,
   14,
   27,
   44,
   19,
   13,
   37,
   41,
   47,
   31,
   24,
   32,
   20,
   45,
   48,
   2,
   1,
   15,
   39,
   17,
   5,
   6,
   22,
   10,
   9,
   29,
   7,
   26,
   25,
   35,
   23,
   8,
   12,
   28,
   30,
   3,
   43],
  -1))

In [8]:
exp2_results = run_tsp_experiments(100, 2, 3)

Initial solution: [ 0 82 83 30 86  5 44  6 34 73 69 13 76 79  3 70 74 29 50 78  1 41 18 94
 52 26 39 56 77 93 14 89 62 75 53 15 66 57 48 55 28 37 23 27  2 46 65 25
 10 16 95 43 32 91 80 98 67 24 11 92 47 38  7 63 54  4 87 19 17 97 64 90
 81 40 59 21 71  8 61 33  9 96 60 42 31 68 51 22 84 99 45 49 88 36 72 85
 35 12 20 58]
Initial solution cost: 227.60889838545444
Iteration: 0 Current best solution: 227.60889838545444
Best cost updated to:227.1298521645825
Best cost updated to:226.37519568966457
Best cost updated to:225.7853155746247
Best cost updated to:225.73007451209293
Best cost updated to:224.96196102272341
Best cost updated to:224.8503350365745
Best cost updated to:223.86681725885603
Best cost updated to:223.83373719557858
Best cost updated to:223.6664673235308
Best cost updated to:220.74612392892286
Best cost updated to:220.4093508173902
Best cost updated to:220.1225636157051
Resetting candidate solution.
with cost: 930.5858848769435
Resetting candidate solution.
with cost: 908.7

In [9]:
exp2_results

{'sa1': [220.1225636157051, 220.1225636157051, 220.1225636157051],
 'sa1_time': [120.00092434883118, 120.00014877319336, 120.00087285041809],
 'sa2': [206.90516456964988, 206.90516456964988, 206.90516456964988],
 'sa2_time': [120.00696516036987, 120.00700974464417, 120.00608801841736],
 'trad_bnb': [227.60889838545444, 227.60889838545444, 227.60889838545444],
 'trad_bnb_time': [120.10775589942932, 121.97519516944885, 120.27814292907715],
 'mod_bnb': [212.41144104145542, 212.41144104145542, 212.41144104145542],
 'mod_bnb_time': [120.02418160438538, 120.11255359649658, 120.21808981895447],
 'sa1_init_sol': array([ 0, 82, 83, 30, 86,  5, 44,  6, 34, 73, 69, 13, 76, 79,  3, 70, 74,
        29, 50, 78,  1, 41, 18, 94, 52, 26, 39, 56, 77, 93, 14, 89, 62, 75,
        53, 15, 66, 57, 48, 55, 28, 37, 23, 27,  2, 46, 65, 25, 10, 16, 95,
        43, 32, 91, 80, 98, 67, 24, 11, 92, 47, 38,  7, 63, 54,  4, 87, 19,
        17, 97, 64, 90, 81, 40, 59, 21, 71,  8, 61, 33,  9, 96, 60, 42, 31,
        6

In [10]:
exp2_results['sa1_init_sol_cost'], exp2_results['sa1_init_sol']

(227.60889838545444,
 array([ 0, 82, 83, 30, 86,  5, 44,  6, 34, 73, 69, 13, 76, 79,  3, 70, 74,
        29, 50, 78,  1, 41, 18, 94, 52, 26, 39, 56, 77, 93, 14, 89, 62, 75,
        53, 15, 66, 57, 48, 55, 28, 37, 23, 27,  2, 46, 65, 25, 10, 16, 95,
        43, 32, 91, 80, 98, 67, 24, 11, 92, 47, 38,  7, 63, 54,  4, 87, 19,
        17, 97, 64, 90, 81, 40, 59, 21, 71,  8, 61, 33,  9, 96, 60, 42, 31,
        68, 51, 22, 84, 99, 45, 49, 88, 36, 72, 85, 35, 12, 20, 58]))

In [11]:
exp2_results['sa2_init_sol_cost'], exp2_results['sa2_init_sol']

(227.60889838545444,
 [0,
  82,
  83,
  30,
  86,
  5,
  44,
  6,
  34,
  73,
  69,
  13,
  76,
  79,
  3,
  70,
  74,
  29,
  50,
  78,
  1,
  41,
  18,
  94,
  52,
  26,
  39,
  56,
  77,
  93,
  14,
  89,
  62,
  75,
  53,
  15,
  66,
  57,
  48,
  55,
  28,
  37,
  23,
  27,
  2,
  46,
  65,
  25,
  10,
  16,
  95,
  43,
  32,
  91,
  80,
  98,
  67,
  24,
  11,
  92,
  47,
  38,
  7,
  63,
  54,
  4,
  87,
  19,
  17,
  97,
  64,
  90,
  81,
  40,
  59,
  21,
  71,
  8,
  61,
  33,
  9,
  96,
  60,
  42,
  31,
  68,
  51,
  22,
  84,
  99,
  45,
  49,
  88,
  36,
  72,
  85,
  35,
  12,
  20,
  58])

In [12]:
exp2_results['trad_bnb_init_sol_cost'], exp2_results['trad_bnb_init_sol']

(227.60889838545444,
 ([0,
   82,
   83,
   30,
   86,
   5,
   44,
   6,
   34,
   73,
   69,
   13,
   76,
   79,
   3,
   70,
   74,
   29,
   50,
   78,
   1,
   41,
   18,
   94,
   52,
   26,
   39,
   56,
   77,
   93,
   14,
   89,
   62,
   75,
   53,
   15,
   66,
   57,
   48,
   55,
   28,
   37,
   23,
   27,
   2,
   46,
   65,
   25,
   10,
   16,
   95,
   43,
   32,
   91,
   80,
   98,
   67,
   24,
   11,
   92,
   47,
   38,
   7,
   63,
   54,
   4,
   87,
   19,
   17,
   97,
   64,
   90,
   81,
   40,
   59,
   21,
   71,
   8,
   61,
   33,
   9,
   96,
   60,
   42,
   31,
   68,
   51,
   22,
   84,
   99,
   45,
   49,
   88,
   36,
   72,
   85,
   35,
   12,
   20,
   58],
  -1))

In [13]:
exp2_results['mod_bnb_init_sol_cost'], exp2_results['mod_bnb_init_sol']

(227.60889838545444,
 ([0,
   82,
   83,
   30,
   86,
   5,
   44,
   6,
   34,
   73,
   69,
   13,
   76,
   79,
   3,
   70,
   74,
   29,
   50,
   78,
   1,
   41,
   18,
   94,
   52,
   26,
   39,
   56,
   77,
   93,
   14,
   89,
   62,
   75,
   53,
   15,
   66,
   57,
   48,
   55,
   28,
   37,
   23,
   27,
   2,
   46,
   65,
   25,
   10,
   16,
   95,
   43,
   32,
   91,
   80,
   98,
   67,
   24,
   11,
   92,
   47,
   38,
   7,
   63,
   54,
   4,
   87,
   19,
   17,
   97,
   64,
   90,
   81,
   40,
   59,
   21,
   71,
   8,
   61,
   33,
   9,
   96,
   60,
   42,
   31,
   68,
   51,
   22,
   84,
   99,
   45,
   49,
   88,
   36,
   72,
   85,
   35,
   12,
   20,
   58],
  -1))

In [21]:
exp3_results = run_tsp_experiments(200, 4, 3)

Initial solution: [  0 100 169  97 176  43  39  49  79 135 156 136 128  29 163  53 134  61
 129  32 137 124 161 143  27 197  10  70 132  77 126  74  83 118  30  99
 146  89   8  54 175  40  12 119  76 179 185 150 144  67 113   3  94  60
   1  25 127  95 117  84  50  75  73 148 115  47 162  85 174 190  68 182
  98 165 142 196 123  18  41  15 159 160  21 116  55  52 107 158 170  65
  86  34   5  82  20  14  87  93  48 102 153 191 138 149 198  63  81 125
 141  22   6 199  51 178 193 194  69  45 155 164 167  72 173 133  92  88
 109 114 104 154  17  19 166  33 139  23 181  28  62  36   9  35  44 183
 189 151  46 130 195  38 108   4 180 147  26  66  96  64  11  58   7 131
 103  56  90 120 152 171  42 110  91 168 145 157 186  37 140  31   2  13
 187  24  71 188 111 112 122 106  80  78  16 105  59 177  57 172 184 101
 192 121]
Initial solution cost: 307.9864491030866
Iteration: 0 Current best solution: 307.9864491030866
Best cost updated to:307.7505385190836
Best cost updated to:307.1190779368

In [22]:
exp3_results

{'sa1': [303.7366666505149, 303.7366666505149, 303.7366666505149],
 'sa1_time': [240.00069499015808, 240.0046842098236, 240.0127875804901],
 'sa2': [307.9864491030866, 307.9864491030866, 307.9864491030866],
 'sa2_time': [240.01427698135376, 240.00969433784485, 240.0173671245575],
 'trad_bnb': [307.9864491030866, 307.9864491030866, 307.9864491030866],
 'trad_bnb_time': [240.1264307498932, 250.40015745162964, 240.40901255607605],
 'mod_bnb': [288.43990992803106, 288.43990992803106, 288.43990992803106],
 'mod_bnb_time': [240.2265226840973, 240.17677235603333, 243.643940448761],
 'sa1_init_sol': array([  0, 100, 169,  97, 176,  43,  39,  49,  79, 135, 156, 136, 128,
         29, 163,  53, 134,  61, 129,  32, 137, 124, 161, 143,  27, 197,
         10,  70, 132,  77, 126,  74,  83, 118,  30,  99, 146,  89,   8,
         54, 175,  40,  12, 119,  76, 179, 185, 150, 144,  67, 113,   3,
         94,  60,   1,  25, 127,  95, 117,  84,  50,  75,  73, 148, 115,
         47, 162,  85, 174, 190,  68,

In [23]:
exp3_results['sa1_init_sol_cost'], exp3_results['sa1_init_sol']

(307.9864491030866,
 array([  0, 100, 169,  97, 176,  43,  39,  49,  79, 135, 156, 136, 128,
         29, 163,  53, 134,  61, 129,  32, 137, 124, 161, 143,  27, 197,
         10,  70, 132,  77, 126,  74,  83, 118,  30,  99, 146,  89,   8,
         54, 175,  40,  12, 119,  76, 179, 185, 150, 144,  67, 113,   3,
         94,  60,   1,  25, 127,  95, 117,  84,  50,  75,  73, 148, 115,
         47, 162,  85, 174, 190,  68, 182,  98, 165, 142, 196, 123,  18,
         41,  15, 159, 160,  21, 116,  55,  52, 107, 158, 170,  65,  86,
         34,   5,  82,  20,  14,  87,  93,  48, 102, 153, 191, 138, 149,
        198,  63,  81, 125, 141,  22,   6, 199,  51, 178, 193, 194,  69,
         45, 155, 164, 167,  72, 173, 133,  92,  88, 109, 114, 104, 154,
         17,  19, 166,  33, 139,  23, 181,  28,  62,  36,   9,  35,  44,
        183, 189, 151,  46, 130, 195,  38, 108,   4, 180, 147,  26,  66,
         96,  64,  11,  58,   7, 131, 103,  56,  90, 120, 152, 171,  42,
        110,  91, 168, 145, 157

In [24]:
exp3_results['sa1_init_sol_cost'], exp3_results['sa1_init_sol']

(307.9864491030866,
 array([  0, 100, 169,  97, 176,  43,  39,  49,  79, 135, 156, 136, 128,
         29, 163,  53, 134,  61, 129,  32, 137, 124, 161, 143,  27, 197,
         10,  70, 132,  77, 126,  74,  83, 118,  30,  99, 146,  89,   8,
         54, 175,  40,  12, 119,  76, 179, 185, 150, 144,  67, 113,   3,
         94,  60,   1,  25, 127,  95, 117,  84,  50,  75,  73, 148, 115,
         47, 162,  85, 174, 190,  68, 182,  98, 165, 142, 196, 123,  18,
         41,  15, 159, 160,  21, 116,  55,  52, 107, 158, 170,  65,  86,
         34,   5,  82,  20,  14,  87,  93,  48, 102, 153, 191, 138, 149,
        198,  63,  81, 125, 141,  22,   6, 199,  51, 178, 193, 194,  69,
         45, 155, 164, 167,  72, 173, 133,  92,  88, 109, 114, 104, 154,
         17,  19, 166,  33, 139,  23, 181,  28,  62,  36,   9,  35,  44,
        183, 189, 151,  46, 130, 195,  38, 108,   4, 180, 147,  26,  66,
         96,  64,  11,  58,   7, 131, 103,  56,  90, 120, 152, 171,  42,
        110,  91, 168, 145, 157

In [25]:
exp3_results['sa2_init_sol_cost'], exp3_results['sa2_init_sol']

(307.9864491030866,
 [0,
  100,
  169,
  97,
  176,
  43,
  39,
  49,
  79,
  135,
  156,
  136,
  128,
  29,
  163,
  53,
  134,
  61,
  129,
  32,
  137,
  124,
  161,
  143,
  27,
  197,
  10,
  70,
  132,
  77,
  126,
  74,
  83,
  118,
  30,
  99,
  146,
  89,
  8,
  54,
  175,
  40,
  12,
  119,
  76,
  179,
  185,
  150,
  144,
  67,
  113,
  3,
  94,
  60,
  1,
  25,
  127,
  95,
  117,
  84,
  50,
  75,
  73,
  148,
  115,
  47,
  162,
  85,
  174,
  190,
  68,
  182,
  98,
  165,
  142,
  196,
  123,
  18,
  41,
  15,
  159,
  160,
  21,
  116,
  55,
  52,
  107,
  158,
  170,
  65,
  86,
  34,
  5,
  82,
  20,
  14,
  87,
  93,
  48,
  102,
  153,
  191,
  138,
  149,
  198,
  63,
  81,
  125,
  141,
  22,
  6,
  199,
  51,
  178,
  193,
  194,
  69,
  45,
  155,
  164,
  167,
  72,
  173,
  133,
  92,
  88,
  109,
  114,
  104,
  154,
  17,
  19,
  166,
  33,
  139,
  23,
  181,
  28,
  62,
  36,
  9,
  35,
  44,
  183,
  189,
  151,
  46,
  130,
  195,
  38,
  108,
  4,
  

In [26]:
exp3_results['trad_bnb_init_sol_cost'], exp3_results['trad_bnb_init_sol']

(307.9864491030866,
 ([0,
   100,
   169,
   97,
   176,
   43,
   39,
   49,
   79,
   135,
   156,
   136,
   128,
   29,
   163,
   53,
   134,
   61,
   129,
   32,
   137,
   124,
   161,
   143,
   27,
   197,
   10,
   70,
   132,
   77,
   126,
   74,
   83,
   118,
   30,
   99,
   146,
   89,
   8,
   54,
   175,
   40,
   12,
   119,
   76,
   179,
   185,
   150,
   144,
   67,
   113,
   3,
   94,
   60,
   1,
   25,
   127,
   95,
   117,
   84,
   50,
   75,
   73,
   148,
   115,
   47,
   162,
   85,
   174,
   190,
   68,
   182,
   98,
   165,
   142,
   196,
   123,
   18,
   41,
   15,
   159,
   160,
   21,
   116,
   55,
   52,
   107,
   158,
   170,
   65,
   86,
   34,
   5,
   82,
   20,
   14,
   87,
   93,
   48,
   102,
   153,
   191,
   138,
   149,
   198,
   63,
   81,
   125,
   141,
   22,
   6,
   199,
   51,
   178,
   193,
   194,
   69,
   45,
   155,
   164,
   167,
   72,
   173,
   133,
   92,
   88,
   109,
   114,
   104,
   154,
   17,
   1

In [27]:
exp3_results['mod_bnb_init_sol_cost'], exp3_results['mod_bnb_init_sol']

(307.9864491030866,
 ([0,
   100,
   169,
   97,
   176,
   43,
   39,
   49,
   79,
   135,
   156,
   136,
   128,
   29,
   163,
   53,
   134,
   61,
   129,
   32,
   137,
   124,
   161,
   143,
   27,
   197,
   10,
   70,
   132,
   77,
   126,
   74,
   83,
   118,
   30,
   99,
   146,
   89,
   8,
   54,
   175,
   40,
   12,
   119,
   76,
   179,
   185,
   150,
   144,
   67,
   113,
   3,
   94,
   60,
   1,
   25,
   127,
   95,
   117,
   84,
   50,
   75,
   73,
   148,
   115,
   47,
   162,
   85,
   174,
   190,
   68,
   182,
   98,
   165,
   142,
   196,
   123,
   18,
   41,
   15,
   159,
   160,
   21,
   116,
   55,
   52,
   107,
   158,
   170,
   65,
   86,
   34,
   5,
   82,
   20,
   14,
   87,
   93,
   48,
   102,
   153,
   191,
   138,
   149,
   198,
   63,
   81,
   125,
   141,
   22,
   6,
   199,
   51,
   178,
   193,
   194,
   69,
   45,
   155,
   164,
   167,
   72,
   173,
   133,
   92,
   88,
   109,
   114,
   104,
   154,
   17,
   1