In [1]:
from optimizn.experiments.tsp.tsp_experiments import run_tsp_experiments

In [2]:
exp1_results = run_tsp_experiments(50, 1, 3)

Initial solution: [ 0 26 29 46  9 48 27 34 19 42 36  4  1  6 38 24 40 31 14 10 41 33 30  5
 13 20 49 35 39 47 43 28 17 22 11 37 32  8 45 16  3 18 15 12 23  7 25  2
 44 21]
Initial solution cost: 179.54400838440995
Iteration: 0 Current best solution: 179.54400838440995
Best cost updated to:179.35679829400337
Best cost updated to:178.5997295226999
Best cost updated to:172.26659794193964
Best cost updated to:171.93176273298215
Best cost updated to:170.67746545297666
Best cost updated to:160.47066728964634
Best cost updated to:157.1536376268052
Best cost updated to:156.85843773432197
Best cost updated to:156.00263831335872
Best cost updated to:152.71228523460354
Best cost updated to:148.3696926866365
Best cost updated to:147.41160983199376
Best cost updated to:147.24685802984382
Best cost updated to:146.39926347238242
Best cost updated to:145.97333253647344
Best cost updated to:143.47411262689533
Switching to a completely random solution.
with cost: 479.02596211839364
Iteration: 10000 Curr

c:\Users\asathiya\anaconda3\envs\optimizn\lib\site-packages\optimizn-0.0.7-py3.9.egg\optimizn\combinatorial\anneal.py:64: RuntimeWarning: overflow encountered in exp
  eps = np.exp(cost_del / temprature)


Switching to a completely random solution.
with cost: 484.4622776481548
Switching to a completely random solution.
with cost: 461.15834723483493
Switching to a completely random solution.
with cost: 507.5259977581567
Iteration: 210000 Current best solution: 143.47411262689533
Iteration: 220000 Current best solution: 143.47411262689533
Switching to a completely random solution.
with cost: 461.6347728350331
Iteration: 230000 Current best solution: 143.47411262689533
Iteration: 240000 Current best solution: 143.47411262689533
Iteration: 250000 Current best solution: 143.47411262689533
Switching to a completely random solution.
with cost: 449.9990931656805
Switching to a completely random solution.
with cost: 501.4332512322529
Iteration: 260000 Current best solution: 143.47411262689533
Iteration: 270000 Current best solution: 143.47411262689533
Switching to a completely random solution.
with cost: 459.3413951374895
Iteration: 280000 Current best solution: 143.47411262689533
Switching to a 

In [3]:
exp1_results

{'sa1': [143.47411262689533, 143.47411262689533, 143.47411262689533],
 'sa1_time': [60.00493836402893, 60.00057554244995, 60.000308990478516],
 'sa2': [140.8493615842254, 140.8493615842254, 139.62712491814463],
 'sa2_time': [60.019771099090576, 60.0048086643219, 60.00087118148804],
 'trad_bnb': [179.54400838440995, 179.54400838440995, 179.54400838440995],
 'trad_bnb_time': [60.08563423156738, 60.20987272262573, 60.32986569404602],
 'mod_bnb': [145.62919998005327, 145.62919998005327, 145.62919998005327],
 'mod_bnb_time': [60.01049017906189, 60.1122190952301, 60.12487077713013],
 'sa1_init_sol': array([ 0, 26, 29, 46,  9, 48, 27, 34, 19, 42, 36,  4,  1,  6, 38, 24, 40,
        31, 14, 10, 41, 33, 30,  5, 13, 20, 49, 35, 39, 47, 43, 28, 17, 22,
        11, 37, 32,  8, 45, 16,  3, 18, 15, 12, 23,  7, 25,  2, 44, 21]),
 'sa1_init_sol_cost': 179.54400838440995,
 'sa2_init_sol': [0,
  26,
  29,
  46,
  9,
  48,
  27,
  34,
  19,
  42,
  36,
  4,
  1,
  6,
  38,
  24,
  40,
  31,
  14,
  10,
 

In [4]:
exp1_results['sa1_init_sol_cost'], exp1_results['sa1_init_sol']

(179.54400838440995,
 array([ 0, 26, 29, 46,  9, 48, 27, 34, 19, 42, 36,  4,  1,  6, 38, 24, 40,
        31, 14, 10, 41, 33, 30,  5, 13, 20, 49, 35, 39, 47, 43, 28, 17, 22,
        11, 37, 32,  8, 45, 16,  3, 18, 15, 12, 23,  7, 25,  2, 44, 21]))

In [5]:
exp1_results['sa2_init_sol_cost'], exp1_results['sa2_init_sol']

(179.54400838440995,
 [0,
  26,
  29,
  46,
  9,
  48,
  27,
  34,
  19,
  42,
  36,
  4,
  1,
  6,
  38,
  24,
  40,
  31,
  14,
  10,
  41,
  33,
  30,
  5,
  13,
  20,
  49,
  35,
  39,
  47,
  43,
  28,
  17,
  22,
  11,
  37,
  32,
  8,
  45,
  16,
  3,
  18,
  15,
  12,
  23,
  7,
  25,
  2,
  44,
  21])

In [6]:
exp1_results['trad_bnb_init_sol_cost'], exp1_results['trad_bnb_init_sol']

(179.54400838440995,
 ([0,
   26,
   29,
   46,
   9,
   48,
   27,
   34,
   19,
   42,
   36,
   4,
   1,
   6,
   38,
   24,
   40,
   31,
   14,
   10,
   41,
   33,
   30,
   5,
   13,
   20,
   49,
   35,
   39,
   47,
   43,
   28,
   17,
   22,
   11,
   37,
   32,
   8,
   45,
   16,
   3,
   18,
   15,
   12,
   23,
   7,
   25,
   2,
   44,
   21],
  -1))

In [7]:
exp1_results['mod_bnb_init_sol_cost'], exp1_results['mod_bnb_init_sol']

(179.54400838440995,
 ([0,
   26,
   29,
   46,
   9,
   48,
   27,
   34,
   19,
   42,
   36,
   4,
   1,
   6,
   38,
   24,
   40,
   31,
   14,
   10,
   41,
   33,
   30,
   5,
   13,
   20,
   49,
   35,
   39,
   47,
   43,
   28,
   17,
   22,
   11,
   37,
   32,
   8,
   45,
   16,
   3,
   18,
   15,
   12,
   23,
   7,
   25,
   2,
   44,
   21],
  -1))

In [8]:
exp2_results = run_tsp_experiments(100, 2, 3)

Initial solution: [ 0 34  6 73  8 20 90  1 95 31 78 56 18 94 79 14 75 54  2 41 88 10 84 38
 48 65 58 19 35 46 77 85 22 26 80 98 43 23 87 33 40 96  7 45 44 82 11 71
 24 37 52 92 12 47  4 86 76 81 16 39 13 42 27 15 60 69 62 28 83  3 51 30
 29 89 93 32 61 21 17 59  9 70 57 64 74 55  5 72 66 91 67 49 63 36 53 97
 68 25 50 99]
Initial solution cost: 196.93925291598202
Iteration: 0 Current best solution: 196.93925291598202
Best cost updated to:189.33089415463888
Best cost updated to:188.59672172920148
Best cost updated to:188.50919817160283
Best cost updated to:188.10138119566372
Best cost updated to:187.65036796622692
Best cost updated to:186.38677919059066
Best cost updated to:186.3778355608751
Best cost updated to:186.2817760201693
Best cost updated to:184.84612421610544
Switching to a completely random solution.
with cost: 901.802688937575
Iteration: 10000 Current best solution: 184.84612421610544
Switching to a completely random solution.
with cost: 900.2591949707147
Iteration: 20000 Cu

In [9]:
exp2_results

{'sa1': [184.84612421610544, 184.84612421610544, 184.84612421610544],
 'sa1_time': [120.00061058998108, 120.00063586235046, 120.00063347816467],
 'sa2': [196.93925291598202, 196.5680303107694, 196.5680303107694],
 'sa2_time': [120.00663137435913, 120.0132999420166, 120.00652027130127],
 'trad_bnb': [196.93925291598202, 196.93925291598202, 196.93925291598202],
 'trad_bnb_time': [120.14334011077881, 120.45322179794312, 132.81675386428833],
 'mod_bnb': [183.0199424357685, 183.0199424357685, 183.0199424357685],
 'mod_bnb_time': [120.04970479011536, 120.14702677726746, 120.36939120292664],
 'sa1_init_sol': array([ 0, 34,  6, 73,  8, 20, 90,  1, 95, 31, 78, 56, 18, 94, 79, 14, 75,
        54,  2, 41, 88, 10, 84, 38, 48, 65, 58, 19, 35, 46, 77, 85, 22, 26,
        80, 98, 43, 23, 87, 33, 40, 96,  7, 45, 44, 82, 11, 71, 24, 37, 52,
        92, 12, 47,  4, 86, 76, 81, 16, 39, 13, 42, 27, 15, 60, 69, 62, 28,
        83,  3, 51, 30, 29, 89, 93, 32, 61, 21, 17, 59,  9, 70, 57, 64, 74,
        55, 

In [10]:
exp2_results['sa1_init_sol_cost'], exp2_results['sa1_init_sol']

(196.93925291598202,
 array([ 0, 34,  6, 73,  8, 20, 90,  1, 95, 31, 78, 56, 18, 94, 79, 14, 75,
        54,  2, 41, 88, 10, 84, 38, 48, 65, 58, 19, 35, 46, 77, 85, 22, 26,
        80, 98, 43, 23, 87, 33, 40, 96,  7, 45, 44, 82, 11, 71, 24, 37, 52,
        92, 12, 47,  4, 86, 76, 81, 16, 39, 13, 42, 27, 15, 60, 69, 62, 28,
        83,  3, 51, 30, 29, 89, 93, 32, 61, 21, 17, 59,  9, 70, 57, 64, 74,
        55,  5, 72, 66, 91, 67, 49, 63, 36, 53, 97, 68, 25, 50, 99]))

In [21]:
exp2_results['sa2_init_sol_cost'], exp2_results['sa2_init_sol']

(196.93925291598202,
 [0,
  34,
  6,
  73,
  8,
  20,
  90,
  1,
  95,
  31,
  78,
  56,
  18,
  94,
  79,
  14,
  75,
  54,
  2,
  41,
  88,
  10,
  84,
  38,
  48,
  65,
  58,
  19,
  35,
  46,
  77,
  85,
  22,
  26,
  80,
  98,
  43,
  23,
  87,
  33,
  40,
  96,
  7,
  45,
  44,
  82,
  11,
  71,
  24,
  37,
  52,
  92,
  12,
  47,
  4,
  86,
  76,
  81,
  16,
  39,
  13,
  42,
  27,
  15,
  60,
  69,
  62,
  28,
  83,
  3,
  51,
  30,
  29,
  89,
  93,
  32,
  61,
  21,
  17,
  59,
  9,
  70,
  57,
  64,
  74,
  55,
  5,
  72,
  66,
  91,
  67,
  49,
  63,
  36,
  53,
  97,
  68,
  25,
  50,
  99])

In [12]:
exp2_results['trad_bnb_init_sol_cost'], exp2_results['trad_bnb_init_sol']

(196.93925291598202,
 ([0,
   34,
   6,
   73,
   8,
   20,
   90,
   1,
   95,
   31,
   78,
   56,
   18,
   94,
   79,
   14,
   75,
   54,
   2,
   41,
   88,
   10,
   84,
   38,
   48,
   65,
   58,
   19,
   35,
   46,
   77,
   85,
   22,
   26,
   80,
   98,
   43,
   23,
   87,
   33,
   40,
   96,
   7,
   45,
   44,
   82,
   11,
   71,
   24,
   37,
   52,
   92,
   12,
   47,
   4,
   86,
   76,
   81,
   16,
   39,
   13,
   42,
   27,
   15,
   60,
   69,
   62,
   28,
   83,
   3,
   51,
   30,
   29,
   89,
   93,
   32,
   61,
   21,
   17,
   59,
   9,
   70,
   57,
   64,
   74,
   55,
   5,
   72,
   66,
   91,
   67,
   49,
   63,
   36,
   53,
   97,
   68,
   25,
   50,
   99],
  -1))

In [13]:
exp2_results['mod_bnb_init_sol_cost'], exp2_results['mod_bnb_init_sol']

(196.93925291598202,
 ([0,
   34,
   6,
   73,
   8,
   20,
   90,
   1,
   95,
   31,
   78,
   56,
   18,
   94,
   79,
   14,
   75,
   54,
   2,
   41,
   88,
   10,
   84,
   38,
   48,
   65,
   58,
   19,
   35,
   46,
   77,
   85,
   22,
   26,
   80,
   98,
   43,
   23,
   87,
   33,
   40,
   96,
   7,
   45,
   44,
   82,
   11,
   71,
   24,
   37,
   52,
   92,
   12,
   47,
   4,
   86,
   76,
   81,
   16,
   39,
   13,
   42,
   27,
   15,
   60,
   69,
   62,
   28,
   83,
   3,
   51,
   30,
   29,
   89,
   93,
   32,
   61,
   21,
   17,
   59,
   9,
   70,
   57,
   64,
   74,
   55,
   5,
   72,
   66,
   91,
   67,
   49,
   63,
   36,
   53,
   97,
   68,
   25,
   50,
   99],
  -1))

In [14]:
exp3_results = run_tsp_experiments(200, 4, 3)

Initial solution: [  0  42  25 186  55 199 175  83  48  62  56 173  45  65 158  66 123 132
  53  85 107 193  24  37 152 104  92 100  13  96  26 192   2 116  67 171
  61  70  32  39  59 126  72 124  64 135 102 191 127 149  71 108  82 179
  95 141 154  78  20 106 156 189 165  94  74  47 187  73  98 139 148 101
 142  44  84  28 131   7 113 153  16  30  81 184  33  22   8 195  21 117
  58  14 110  89  57  97 140  23 162  90 160  49 145 188  35  46 159 133
  99 114 147   5  29  43 196  68  38 134 130 172 136  15 143 109  79 198
 121   4 146 176 150  88 103 169  86 190 144 177  36 161  10 174 157  80
  54  50  18 181  69   9  11 119 112 164 170 129 180  60 168  77  17 125
  19 120  93   1 182  31 163 137 111  91  52  40  87  51  63  34 122  41
 118 115  75 178 151   3 128 183 105 194  76 155 167 138   6  12  27 197
 185 166]
Initial solution cost: 293.08684945506013
Iteration: 0 Current best solution: 293.08684945506013
Best cost updated to:292.6349466477777
Best cost updated to:292.59873961

In [15]:
exp3_results

{'sa1': [292.5317142689334, 292.5317142689334, 292.5317142689334],
 'sa1_time': [240.00093626976013, 240.0004370212555, 240.00010752677917],
 'sa2': [293.08684945506013, 293.08684945506013, 293.08684945506013],
 'sa2_time': [240.0114848613739, 240.01121854782104, 240.01218485832214],
 'trad_bnb': [293.08684945506013, 293.08684945506013, 293.08684945506013],
 'trad_bnb_time': [240.18908953666687, 240.33595275878906, 240.45227575302124],
 'mod_bnb': [269.84357113513624, 269.84357113513624, 269.84357113513624],
 'mod_bnb_time': [240.30939984321594, 240.22505903244019, 240.37646198272705],
 'sa1_init_sol': array([  0,  42,  25, 186,  55, 199, 175,  83,  48,  62,  56, 173,  45,
         65, 158,  66, 123, 132,  53,  85, 107, 193,  24,  37, 152, 104,
         92, 100,  13,  96,  26, 192,   2, 116,  67, 171,  61,  70,  32,
         39,  59, 126,  72, 124,  64, 135, 102, 191, 127, 149,  71, 108,
         82, 179,  95, 141, 154,  78,  20, 106, 156, 189, 165,  94,  74,
         47, 187,  73,  98

In [16]:
exp3_results['sa1_init_sol_cost'], exp3_results['sa1_init_sol']

(293.08684945506013,
 array([  0,  42,  25, 186,  55, 199, 175,  83,  48,  62,  56, 173,  45,
         65, 158,  66, 123, 132,  53,  85, 107, 193,  24,  37, 152, 104,
         92, 100,  13,  96,  26, 192,   2, 116,  67, 171,  61,  70,  32,
         39,  59, 126,  72, 124,  64, 135, 102, 191, 127, 149,  71, 108,
         82, 179,  95, 141, 154,  78,  20, 106, 156, 189, 165,  94,  74,
         47, 187,  73,  98, 139, 148, 101, 142,  44,  84,  28, 131,   7,
        113, 153,  16,  30,  81, 184,  33,  22,   8, 195,  21, 117,  58,
         14, 110,  89,  57,  97, 140,  23, 162,  90, 160,  49, 145, 188,
         35,  46, 159, 133,  99, 114, 147,   5,  29,  43, 196,  68,  38,
        134, 130, 172, 136,  15, 143, 109,  79, 198, 121,   4, 146, 176,
        150,  88, 103, 169,  86, 190, 144, 177,  36, 161,  10, 174, 157,
         80,  54,  50,  18, 181,  69,   9,  11, 119, 112, 164, 170, 129,
        180,  60, 168,  77,  17, 125,  19, 120,  93,   1, 182,  31, 163,
        137, 111,  91,  52,  4

In [17]:
exp3_results['sa1_init_sol_cost'], exp3_results['sa1_init_sol']

(293.08684945506013,
 array([  0,  42,  25, 186,  55, 199, 175,  83,  48,  62,  56, 173,  45,
         65, 158,  66, 123, 132,  53,  85, 107, 193,  24,  37, 152, 104,
         92, 100,  13,  96,  26, 192,   2, 116,  67, 171,  61,  70,  32,
         39,  59, 126,  72, 124,  64, 135, 102, 191, 127, 149,  71, 108,
         82, 179,  95, 141, 154,  78,  20, 106, 156, 189, 165,  94,  74,
         47, 187,  73,  98, 139, 148, 101, 142,  44,  84,  28, 131,   7,
        113, 153,  16,  30,  81, 184,  33,  22,   8, 195,  21, 117,  58,
         14, 110,  89,  57,  97, 140,  23, 162,  90, 160,  49, 145, 188,
         35,  46, 159, 133,  99, 114, 147,   5,  29,  43, 196,  68,  38,
        134, 130, 172, 136,  15, 143, 109,  79, 198, 121,   4, 146, 176,
        150,  88, 103, 169,  86, 190, 144, 177,  36, 161,  10, 174, 157,
         80,  54,  50,  18, 181,  69,   9,  11, 119, 112, 164, 170, 129,
        180,  60, 168,  77,  17, 125,  19, 120,  93,   1, 182,  31, 163,
        137, 111,  91,  52,  4

In [20]:
exp3_results['sa2_init_sol_cost'], exp3_results['sa2_init_sol']

(293.08684945506013,
 [0,
  42,
  25,
  186,
  55,
  199,
  175,
  83,
  48,
  62,
  56,
  173,
  45,
  65,
  158,
  66,
  123,
  132,
  53,
  85,
  107,
  193,
  24,
  37,
  152,
  104,
  92,
  100,
  13,
  96,
  26,
  192,
  2,
  116,
  67,
  171,
  61,
  70,
  32,
  39,
  59,
  126,
  72,
  124,
  64,
  135,
  102,
  191,
  127,
  149,
  71,
  108,
  82,
  179,
  95,
  141,
  154,
  78,
  20,
  106,
  156,
  189,
  165,
  94,
  74,
  47,
  187,
  73,
  98,
  139,
  148,
  101,
  142,
  44,
  84,
  28,
  131,
  7,
  113,
  153,
  16,
  30,
  81,
  184,
  33,
  22,
  8,
  195,
  21,
  117,
  58,
  14,
  110,
  89,
  57,
  97,
  140,
  23,
  162,
  90,
  160,
  49,
  145,
  188,
  35,
  46,
  159,
  133,
  99,
  114,
  147,
  5,
  29,
  43,
  196,
  68,
  38,
  134,
  130,
  172,
  136,
  15,
  143,
  109,
  79,
  198,
  121,
  4,
  146,
  176,
  150,
  88,
  103,
  169,
  86,
  190,
  144,
  177,
  36,
  161,
  10,
  174,
  157,
  80,
  54,
  50,
  18,
  181,
  69,
  9,
  11,
  119,
 

In [18]:
exp3_results['trad_bnb_init_sol_cost'], exp3_results['trad_bnb_init_sol']

(293.08684945506013,
 ([0,
   42,
   25,
   186,
   55,
   199,
   175,
   83,
   48,
   62,
   56,
   173,
   45,
   65,
   158,
   66,
   123,
   132,
   53,
   85,
   107,
   193,
   24,
   37,
   152,
   104,
   92,
   100,
   13,
   96,
   26,
   192,
   2,
   116,
   67,
   171,
   61,
   70,
   32,
   39,
   59,
   126,
   72,
   124,
   64,
   135,
   102,
   191,
   127,
   149,
   71,
   108,
   82,
   179,
   95,
   141,
   154,
   78,
   20,
   106,
   156,
   189,
   165,
   94,
   74,
   47,
   187,
   73,
   98,
   139,
   148,
   101,
   142,
   44,
   84,
   28,
   131,
   7,
   113,
   153,
   16,
   30,
   81,
   184,
   33,
   22,
   8,
   195,
   21,
   117,
   58,
   14,
   110,
   89,
   57,
   97,
   140,
   23,
   162,
   90,
   160,
   49,
   145,
   188,
   35,
   46,
   159,
   133,
   99,
   114,
   147,
   5,
   29,
   43,
   196,
   68,
   38,
   134,
   130,
   172,
   136,
   15,
   143,
   109,
   79,
   198,
   121,
   4,
   146,
   176,
   150,
   88

In [19]:
exp3_results['mod_bnb_init_sol_cost'], exp3_results['mod_bnb_init_sol']

(293.08684945506013,
 ([0,
   42,
   25,
   186,
   55,
   199,
   175,
   83,
   48,
   62,
   56,
   173,
   45,
   65,
   158,
   66,
   123,
   132,
   53,
   85,
   107,
   193,
   24,
   37,
   152,
   104,
   92,
   100,
   13,
   96,
   26,
   192,
   2,
   116,
   67,
   171,
   61,
   70,
   32,
   39,
   59,
   126,
   72,
   124,
   64,
   135,
   102,
   191,
   127,
   149,
   71,
   108,
   82,
   179,
   95,
   141,
   154,
   78,
   20,
   106,
   156,
   189,
   165,
   94,
   74,
   47,
   187,
   73,
   98,
   139,
   148,
   101,
   142,
   44,
   84,
   28,
   131,
   7,
   113,
   153,
   16,
   30,
   81,
   184,
   33,
   22,
   8,
   195,
   21,
   117,
   58,
   14,
   110,
   89,
   57,
   97,
   140,
   23,
   162,
   90,
   160,
   49,
   145,
   188,
   35,
   46,
   159,
   133,
   99,
   114,
   147,
   5,
   29,
   43,
   196,
   68,
   38,
   134,
   130,
   172,
   136,
   15,
   143,
   109,
   79,
   198,
   121,
   4,
   146,
   176,
   150,
   88